# Generated by Django 2.2.4 on 2019-08-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=156)),
                ('valor', models.CharField(max_length=156)),
                ('obs', models.CharField(blank=True, max_length=156, null=True)),
                ('canal', models.ForeignKey(blank=True, default='TBD', null=True, on_delete=False, to='gerirContatos.CanalContato')),
            ],
        ),
    ]
